version: '3.4'

services:
  app:
    image: django-app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    expose:
      - "8000"
    volumes:
      - static:/app/static
      - media:/app/media

  nginx:
    image: nginx:1.19.4-alpine
    volumes:
      - static:/usr/share/nginx/html/static
      - media:/usr/share/nginx/html/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "8027:80"

volumes:
  static:
  media:
